
from lib.data import insert_dic

def Heisenberg(P):

    L = P['Simulation']['L']

    def_P = {
        'Physical_Bond_Dimension': 2,
        'System': 'Heisenberg',
        'Simulation': {
            'L': L,
            'state': 0,
            'dtype': 'float64',
            'couplings': {
                'J': ['0', '0', '1'],
                'h_x': '0.5',
            },
            'svd': {
                'minimum_value': 1e-8,
                'cutoff': 200,
            },
            'dmrg': {
                'min_sweeps': 4,
                'precision': 1e-6,
            },
        },
        'Fit': {
            'Phase': {
                'threshold': 0.1,
            },
            'Correlation Length': {
                'q_lims': [0, 1],
            },
        },
        'id': L,
        'Phases': {
            'indices': (-1, 0, 1),
            'labels':  ('AF', 'D', 'F'),
            'colors':  ('tab:black', 'white', 'tab:gray'),
        },
    }

    def_P = insert_dic(default(), def_P)
    P = insert_dic(def_P, P)

    return P

def Rydberg(P):

    L = P['Simulation']['L']

    def_P = {
        'Physical_Bond_Dimension': 2,
        'System': 'Rydberg',
        'Simulation': {
            'L': L,
            'state': 0,
            'dtype': 'float64',
            'couplings': {
                'V': '1',
                'x': '1',
                'y': '1',
            },
            'svd': {
                'minimum_value': 1e-8,
                'cutoff': 200,
            },
            'dmrg': {
                'min_sweeps': 4,
                'precision': 5e-6,
            },
            'power_law': {
                'exp_terms': 12,
                'cutoff': L,
                'fit': {
                    'precision': 1e-14,
                    'max_iterations': 6000,
                }
            },
        },
        'Fit': {
            'Phase': {
                'periods': (2, 3, 4, 5),
                'expected_period': None,
                'Threshold': {
                    'order_parameter': 1.5e-1,
                    'occupation': 0.1,
                    'commensurate': 8e-3,
                    'floating': 0.001,
                    'min_c': 1,
                },
            },
            'Scaling Dimension': {
                'fit': True,
            },
            'Correlation Length': {
                'q_lims': [0.15, 0.55],
            },
        },
        'id': L,
        'Phases': {
            'indices': (-1,            0,         1,           2,           3,            4,          5,        ),
            'labels':  ('FL',          'ID',      'CD',        '1/2',       '1/3',        '1/4',      '1/5',    ),
            'colors':  ('tab:gray',    '#ebebeb', 'black',     'tab:green', 'tab:orange', 'tab:blue', 'tab:red',),
        },
    }

    P = insert_dic(default(), def_P)
    P = insert_dic(def_P, P)

    return P


def default():

    return {
        'Lanczos': {
            'vectors': 100,
            'max_iterations': 300,
            'precision': 1e-9,
        },
        'Measure': {
            'one_point': {'measure': True},
            'nn_two_point': {'measure': True},
            'two_point': {'measure': True},
            'full_two_point': {
                'measure': False,
                'max_distance': 5,
                'points': 5,
            },
        },
        'Fit': {
            'linearize': 6,
            'Least Squares': {
                'max_iterations': 6000,
                'precision': 1e-14,
            },
            'Phase': {
                'expected_period': None,
            },
            'Scaling Dimension': {
                'plot': True,
                'fit': False,
                'x_lims': [0.9, 0.9999],
                'shift': '0',
            },
            'Central Charge': {
                'fit': True,
                'plot': True,
                'x_lims': [0.9, 0.9999],
                'points': [3, 1000],
            },
            'Correlation Length': {
                'fit': True,
                'plot': True,
                'repeats': [1.],
                'force': False,
                'print': False,
                'q_start': 'auto',
                'q_points': 10000,
                'q_lims': [0, 1],
                'x_lims': [0.2, 0.6],
                'error_threshold': 1e-11,
                'exponent': 1/2,
            },
        },
        'Initialization': {
            'use_temp_mps': True,
            'use_start_mps': True,
            'require_start_mps': False,
            'replace': False,
            'max_length_difference': 30,
            'max_distance': 0,
            'Cutoff': {
                'growth': 30,
                'initial_not_same': 50,
                'initial_same': 100,
                'restarted': 120,
            },
            'ED': {'use': True, 'L': 12},
            'random': {'L': 4},
        },
        'Data': {
            'folder': '.',
            'subsets': [{}],
            'linear_range': None,
            'grid': None,
            'set': None,
            'only_edges': False,
            'tags': ['test'],
        },
        'Run': {
            'remeasure': False,
            'refit': False,
            'sleep': 0.02,
            'max_sweeps': 12,
            'stop_at_max_D': False,
            'stop_if_initial_same': True,
            'memory_margin': 3.,
        },
        'Clean': {
            'files': [],
            'keep_if': ['MPS', 'temp_MPS', '.running'],
        },
        'Exponent': {
            'ξ': {
                'plot': False,
                'log': False,
                'label': '1/ξ',
                'invert': True,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': None,
                'Error': {
                    'minimum': 0.002,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 1,
                    'exp': 'ν',
                },
            },
            'q': {
                'plot': False,
                'log': False,
                'label': 'q',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': 'ξ',
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 2,
                    'exp': '\\bar{β}',
                },
            },
            'R': {
                'plot': False,
                'log': False,
                'label': 'ξ|q-1/p|',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': 'ξ',
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 2,
                    'exp': 't',
                },
            },
            'c': {
                'plot': False,
                'log': False,
                'label': 'c',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': 'ξ',
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 0,
                    'exp': 'g',
                },
            },
            'E': {
                'plot': False,
                'log': False,
                'label': 'E',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': 'ξ',
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 2,
                    'exp': 'α',
                },
            },
            'd': {
                'plot': False,
                'log': False,
                'label': 'd',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': 'ξ',
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 2,
                    'exp': 'b',
                },
            },
            'O': {
                'plot': False,
                'log': True,
                'label': 'O',
                'invert': False,
                'x_shift': None,
                'shift': 0,
                'rm': [],
                'x_lims': [-1e10, 1e10],
                'lims': [1e-10, 1e10],
                'add_crit_line': None,
                'Error': {
                    'minimum': 0,
                },
                'Fit': {
                    'plot': False,
                    'crit_point': None,
                    'rm': [],
                    'x_start': None,
                    'x_lims': [-1e10, 1e10],
                    'lims': [1e-10, 1e10],
                    'expected': None,
                    'extend': 2,
                    'exp': 'β',
                },
            },
        },
        'Exponent_Properties': {
            'size': [1, 1],
            'data': {
                61: {
                    'linestyle': '',
                    'color': 'tab:olive',
                    'marker': 'o',
                    'fillstyle': 'none',
                    'markerfacecolor': 'tab:olive',
                    'markeredgecolor': 'tab:olive',
                    'markersize': 1.5,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
                121: {
                    'linestyle': '',
                    'color': 'tab:purple',
                    'marker': 'X',
                    'fillstyle': 'none',
                    'markerfacecolor': 'tab:purple',
                    'markeredgecolor': 'tab:purple',
                    'markersize': 1.5,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
                181: {
                    'linestyle': '',
                    'color': 'tab:cyan',
                    'marker': '^',
                    'fillstyle': 'none',
                    'markerfacecolor': 'tab:cyan',
                    'markeredgecolor': 'tab:cyan',
                    'markersize': 1.5,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
                241: {
                    'linestyle': '',
                    'color': 'black',
                    'marker': '*',
                    'fillstyle': 'none',
                    'markerfacecolor': 'black',
                    'markeredgecolor': 'black',
                    'markersize': 1.5,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
                301: {
                    'linestyle': '',
                    'color': 'tab:orange',
                    'marker': 's',
                    'fillstyle': 'none',
                    'markerfacecolor': 'tab:orange',
                    'markeredgecolor': 'tab:orange',
                    'markersize': 1.5,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
                601: {
                    'linestyle': '',
                    'color': 'tab:red',
                    'marker': '.',
                    'fillstyle': 'none',
                    'markerfacecolor': 'tab:red',
                    'markeredgecolor': 'tab:red',
                    'markersize': 3,
                    'elinewidth': None,
                    'capsize': 0.8,
                },
            },
            'fit_data': {
                61: {
                    'linestyle': '',
                    'color': 'tab:olive',
                    'marker': 'o',
                    'fillstyle': 'full',
                    'markerfacecolor': 'tab:olive',
                    'markeredgecolor': 'tab:olive',
                    'markersize': 1.5,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
                121: {
                    'linestyle': '',
                    'color': 'tab:purple',
                    'marker': 'X',
                    'fillstyle': 'full',
                    'markerfacecolor': 'tab:purple',
                    'markeredgecolor': 'tab:purple',
                    'markersize': 1.5,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
                181: {
                    'linestyle': '',
                    'color': 'tab:cyan',
                    'marker': '^',
                    'fillstyle': 'full',
                    'markerfacecolor': 'tab:cyan',
                    'markeredgecolor': 'tab:cyan',
                    'markersize': 1.5,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
                241: {
                    'linestyle': '',
                    'color': 'black',
                    'marker': '*',
                    'fillstyle': 'full',
                    'markerfacecolor': 'black',
                    'markeredgecolor': 'black',
                    'markersize': 1.5,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
                301: {
                    'linestyle': '',
                    'color': 'tab:orange',
                    'marker': 's',
                    'fillstyle': 'full',
                    'markerfacecolor': 'tab:orange',
                    'markeredgecolor': 'tab:orange',
                    'markersize': 1.5,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
                601: {
                    'linestyle': '',
                    'color': 'tab:red',
                    'marker': '.',
                    'fillstyle': 'full',
                    'markerfacecolor': 'tab:red',
                    'markeredgecolor': 'tab:red',
                    'markersize': 3,
                    'elinewidth': 0.5,
                    'capsize': 0.8,
                },
            },
            'fit': {
                61: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'tab:pink',
                },
                121: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'tab:gray',
                },
                181: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'tab:brown',
                },
                241: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'blue',
                },
                301: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'tab:blue',
                },
                601: {
                    'linestyle': '-',
                    'linewidth': 0.5,
                    'color': 'tab:green',
                },
            },
            'critical_point': {
                61: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'tab:olive',
                    'zorder': 0,
                },
                121: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'tab:purple',
                    'zorder': 0,
                },
                181: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'tab:cyan',
                    'zorder': 0,
                },
                241: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'black',
                    'zorder': 0,
                },
                301: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'tab:orange',
                    'zorder': 0,
                },
                601: {
                    'linestyle': '-',
                    'linewidth': 0.3,
                    'color': 'tab:red',
                    'zorder': 0,
                },
            },
        },
        'Scatter': {
            'p': {
                'plot': False,
                'colorbar': False,
                'boundary': False,
                'label':  'p',
                'points': [],
                'lines':  [],
                'Contour': {
                    'plot':      False,
                    'quantity':  'q',
                    'label':     'q',
                    'accuracy':  4,
                    'add_lines': [],
                    'rm_lines':  [],
                    'lims':      (0, 1, 11),
                },
                'Boundaries': {
                    'plot': False,
                    'extend': [0, 0],
                    'add_line': [],
                    'connect': [],
                },
            },
            'O': {
                'plot': False,
                'colorbar': False,
                'boundary': False,
                'label':  'O',
                'points': [],
                'lines':  [],
                'Contour': {
                    'plot':     False,
                    'quantity': 'q',
                    'label':    'q',
                    'accuracy': 4,
                    'add_lines': [],
                    'rm_lines':  [],
                    'lims':      (0, 1, 11),
                },
            },
            'q': {
                'plot': False,
                'colorbar': False,
                'boundary': False,
                'label':  'q',
                'points': [],
                'lines':  [],
                'Contour': {
                    'plot':     False,
                    'quantity': 'O',
                    'label':    'O',
                    'accuracy': 4,
                    'add_lines': [],
                    'rm_lines':  [],
                    'lims':     (-1, 5, 6),
                },
            },
            'ξ': {
                'plot': False,
                'colorbar': False,
                'boundary': False,
                'label':  'ξ',
                'points': [],
                'lines':  [],
                'Contour': {
                    'plot':     False,
                    'quantity': 'q',
                    'label':    'q',
                    'accuracy': 4,
                    'add_lines': [],
                    'rm_lines':  [],
                    'lims':     (0, 1, 11),
                },
            },
            'c': {
                'plot': False,
                'colorbar': False,
                'boundary': False,
                'label':  'c',
                'points': [],
                'lines':  [],
                'Contour': {
                    'plot':     False,
                    'quantity': 'q',
                    'label':    'q',
                    'accuracy': 4,
                    'add_lines': [],
                    'rm_lines':  [],
                    'lims':     (0, 1, 11),
                },
            },
        },
        'Scatter_Properties': {
            'size': [1, 2],
            'Colormesh': {
                    'cmap': 'Purples',
                    'edgecolors': 'face',
                    'shading': 'nearest',
                    'antialiased': True,
                    'linewidth': 0,
            },
            'Colorbar': {
                'fraction': 0.001,
                'shrink': 0.7,
                'aspect': 35,
                'pad': 0,
            },
            'Contour': {
                'colors': '#53c2e6',
                'linewidths': 0.4,
            },
            'Contour_special': {
                'colors': '#cc471e',
                'linewidths': 0.4,
            },
            'Contour_label': {
                'inline': True,
                'inline_spacing': 2,
                'fontsize': 5,
                'zorder': 10,
            },
            'Lines': {
                'color': '#111111',
                'linewidth': 0.5,
                'zorder': 8,
            },
            'Points': {
                'color': 'black',
                'marker': '.',
                'markersize': 4,
                'zorder': 9,
            },
        },
        'Legend': {
            'loc': 'best',
        },
    }

